apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  ports:
  - name: webapp-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: web-app