apiVersion: v1
kind: Service
metadata:
  run: webapp-service
  labels:
    run: web-app
spec:
  type: LoadBalancer
  ports:
  - name: webapp-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: web-app
    